export const genres = [
    {id: '1', name: 'Action'},
    {id: '2', name: 'Adventure'},
    {id: '4', name: 'Comedy'},
    {id: '6', name: 'Demon'},
    {id: '7', name: 'Mystery'},
    {id: '8', name: 'Drama'},
    {id: '9', name: 'Ecchi'},
    {id: '10', name: 'Fantasy'},
    {id: '11', name: 'Game'},
    {id: '12', name: 'Hentai'},
    {id: '13', name: 'Historical'},
    {id: '14', name: 'Horror'},
    {id: '15', name: 'Kids'},
    {id: '18', name: 'Mecha'},
    {id: '19', name: 'Music'},
    {id: '20', name: 'Parody'},
    {id: '22', name: 'Romance'},
    {id: '23', name: 'School'},
    {id: '24', name: 'Sci Fi'},
    {id: '25', name: 'Shoujo'},
    {id: '27', name: 'Shounen'},
    {id: '30', name: 'Sports'},
    {id: '35', name: 'Harem'},
    {id: '36', name: 'Slice  Of Life'},
    {id: '37', name: 'Supernatural'},
    {id: '38', name: 'Military'},
]